### ISSUE TITLE
Keep the develop branch instead of dev

### ISSUE THREAD

**Issue by qqeasonchen** [apache/eventmesh-dashboard#36]
The name of branch dev is not regular and standard, I suggest a change to develop.

**Comment by Pil0tXia** [comment]
>The name of branch dev is not regular and standard

The names 'dev' and 'develop' are both widely used. Typically, we use nouns to name a branch, with 'dev' abbreviation representing the noun 'development,' while 'develop' is a verb. Additionally, 'dev' is shorter than 'develop' while conveying the same meaning.

In the early stages of developing the admin dashboard, active contributors have already agreed upon using the 'dev' branch naming convention and have been developing on their forked repositories with the 'dev' branch. Transitioning to the 'develop' branch may require additional notification.

I personally find the current 'dev' designation suitable, but if you believe that 'develop' is indeed a better name and a change is necessary, I am willing to make the corresponding adjustments accordingly.

**Comment by Pil0tXia** [comment]
I have reviewed most of the popular Apache projects, and the majority of them do not have a "dev" or "develop" branch 😂; Doris and DolphinScheduler use the "dev" branch, while RocketMQ and Seata use the "develop" branch. This seems to be related to the developers' personal practices.

**Comment by Pil0tXia** [comment]
Completed in https://github.com/apache/eventmesh-dashboard/pull/93
