### ISSUE TITLE
[Feature] Add a client(SDK) manager

### ISSUE THREAD

**Issue by Lambert-Rao** [apache/eventmesh-dashboard#60]
SDK manager holds a map of SDK clients, when used, you can get a client, just provide the server address, if the client not exist, the manager will create one and store it in the map.

**Comment by Lambert-Rao** [comment]
@Pil0tXia the name `SDKManager` okay?

**Comment by Pil0tXia** [comment]
good idea

**Comment by Lambert-Rao** [comment]
feature merged
