### ISSUE TITLE
[Feature] Remoting Service Interface

### ISSUE THREAD

**Issue by Lambert-Rao** [apache/eventmesh-dashboard#73]
@Pil0tXia 
I'm going to provide a bunch of interface of operating remote eventmesh cluster, such as create topic, get cosumer group, etc.
Should I place this in the service module? I found `eventmesh/dashboard/service/meta`:`ConnectionCore`. Is this the same as the `remoting service` mentioned above? If so, I just change my name remoting service into `xxxcore`.
Also, do all of these services return `Result<T>`? I just create a class `CreateTopicResult` like this:
```java
public class CreateTopicResult {
    CompletableFuture<CreateTopicResponse> createTopicResponseFuture;
}
```
I need the `CompletableFuture` to provide async operation.

---
current designed service
```java
AclRemotingService
ClientRemotingService
ConfigRemotingService
ConnectRemotingService
GroupRemotingService
OffsetRemotingService
RelationRemotingService
TopicRemotingService
UserRemotingService
```
---
I will implement the offset service(get and reset storage offset)

**Comment by Lambert-Rao** [comment]
Different service maybe have different async strategy, I want to keep separate Result model

**Comment by Pil0tXia** [comment]
>Is this the same as the remoting service mentioned above?

yes

>If so, I just change my name remoting service into xxxcore.

You may rename at your will.

>do all of these services return Result<T>?

`Result` is returned to frontend only. The dto in application should define a new one.
